const deStrings: Record<string, string> = {
    RATE_LIMIT_WARNING: '⚠️ Sie können nur einmal innerhalb von 10 Minuten eine Wettermeldung absetzen.',
    REPORT_SUCCESS: 'Wettermeldung erfolgreich gesendet!',
    REPORT_ERROR: 'Fehler beim Senden der Wettermeldung!',
    BACK: 'Zurück',
    NEXT: 'Weiter',
    CATEGORIES_TITLE: 'Kategorien',
    LOCATION_TITLE: 'Standort',
    TIME_TITLE: 'Zeit',
    TIME_NOW: 'jetzt',
    TIME_10_MINUTES: 'vor 10 Minuten',
    TIME_20_MINUTES: 'vor 20 Minuten',
    TIME_30_MINUTES: 'vor 30 Minuten',
    TIME_60_MINUTES: 'vor eine Stunde',
    IMAGE_UPLOAD_TITLE: 'Bild hochladen',
    IMAGE_UPLOAD_DESCRIPTION: 'Laden Sie ein Bild hoch (max. 10MB). Unterstützte Formate: JPG, PNG, GIF, WEBP',
    IMAGE_UPLOAD_SUCCESS: '✅ Bild erfolgreich hochgeladen!',
    IMAGE_UPLOAD_REMOVE: 'Bild entfernen',
    IMAGE_UPLOAD_PROGRESS: 'Hochladen...',
    IMAGE_UPLOAD_DROP_FILE: 'Datei hier ablegen...',
    IMAGE_UPLOAD_SELECT: 'Bild auswählen',
    IMAGE_UPLOAD_HINT: 'Klicken Sie, um eine Datei auszuwählen, oder ziehen Sie eine Datei hierher',
    IMAGE_UPLOAD_DRAG_INSTRUCTION: 'oder hier hineinziehen',
    IMAGE_UPLOAD_PREVIEW_ALT: 'Vorschau',
    ERROR_FILE_TOO_LARGE: 'Datei ist zu groß. Maximale Größe: 10MB',
    ERROR_INVALID_FILE_TYPE: 'Nur Bilddateien sind erlaubt (JPG, PNG, GIF, WEBP)',
    ERROR_GENERIC_UPLOAD: 'Fehler beim Hochladen der Datei',
    ERROR_NETWORK_UPLOAD: 'Netzwerkfehler beim Hochladen',
    ERROR_UPLOAD_WITH_STATUS: 'Fehler beim Hochladen:',

    BLITZE: 'Blitze',
    DONNER_UMGEBUNG: 'Donner in der Umgebung',
    BLITZE_EINZELNE: 'schwach',
    BLITZE_HAEUFIG: 'stark',
    BLITZE_EXTREM: 'extrem',

    WIND: 'Wind',
    WIND_SCHWACH: 'schwach',
    WIND_STARK: 'stark',
    WIND_STUERMISCH: 'stürmisch',
    WIND_STURM: 'Sturm',
    WIND_ORKAN: 'Orkan',

    HAGEL: 'Hagel',
    HAGEL_UNTER_1CM: 'unter 1 cm',
    HAGEL_1CM: '1 cm',
    HAGEL_2CM: '2 cm',
    HAGEL_3CM: '3 cm',
    HAGEL_5CM: '5 cm',
    HAGEL_UEBER_7CM: 'über 7 cm',

    HAGEL_GESCHLOSSENE_HAGELDECKE: 'geschlossene Hageldecke',
    HAGEL_SCHADEN_PFLANZEN: 'Schäden an Pflenzen',
    HAGEL_SCHADEN_DACHFENSTER: 'Bruch von Dachfenstern und Gewächshäusern',
    HAGEL_SCHADEN_VEREINZELT: 'vereinzelte Schäden an Dachziegel, Fensterscheiben und Fassaden',
    HAGEL_SCHADEN_ZERSTOERERISCH: 'zerstörische Schäden an Dächern, Fenstern und Fahrzeugen',

    REGEN: 'Regen',
    REGEN_LEICHT: 'leicht',
    REGEN_MITTEL: 'mittel',
    REGEN_KRAEFTIG: 'kräftig',
    REGEN_STARK: 'stark',
    REGEN_EXTREM: 'extrem',

    GLAETTE: 'Glätte',
    GLAETTE_REIF: 'Reifglätte',
    GLAETTE_SCHNEE: 'Schneeglätte',
    GLAETTE_UEBERFRIERENDE_NAESSE: 'überfrierende Nässe',
    GLAETTE_GEFRIERENDER_REGEN: 'gefrierender Regen',

    GLAETTE_GESCHLOSSENE_SCHICHT: 'geschlossene Schicht',
    GLAETTE_DICKE_ICE_UEBER_1CM: 'über 1 cm (Fingerdick',
    GLAETTE_DICKE_ICE_BIS_1CM: 'unter 1 cm (Wellpappe)',
    GLAETTE_DICKE_SNOW_BIS_5CM: 'unter 5 cm',
    GLAETTE_DICKE_SNOW_BIS_20CM: 'unter 20 cm',
    GLAETTE_DICKE_SNOW_BIS_50CM: 'unter 50 cm',
    GLAETTE_DICKE_SNOW_UEBER_50CM: 'über 50 cm',

    SCHNEEFALL: 'Schneefall',
    SCHNEEFALL_WENIGE_FLOCKEN: 'wenige Flocken',
    SCHNEEFALL_LEICHT: 'leicht',
    SCHNEEFALL_MITTEL: 'mittel',
    SCHNEEFALL_STARK: 'stark',

    SCHNEEDECKE: 'Schneedecke',
    SCHNEEDECKE_SCHNEEMATSCH: 'Schneematsch',
    SCHNEEDECKE_BIS_1CM: 'bis 1 cm',
    SCHNEEDECKE_BIS_3CM: 'bis zu 3 cm',
    SCHNEEDECKE_BIS_5CM: 'bis zu 5 cm',
    SCHNEEDECKE_BIS_10CM: 'bis zu 10 cm',
    SCHNEEDECKE_BIS_20CM: 'bis zu 20 cm',
    SCHNEEDECKE_BIS_50CM: 'bis zu 50 cm',
    SCHNEEDECKE_UEBER_50CM: 'über 50 cm',

    SCHNEEDECKE_FLECKWEISE: 'Schneeflecken',
    SCHNEEDECKE_GESCHLOSSENE_SCHNEEDECKE: 'geschlossene Schneedecke',

    BEWOELKUNG: 'Bewölkung',
    BEWOELKUNG_WOLKENLOS: 'wolkenlos',
    BEWOELKUNG_LEICHT_BEWOELKT: 'leicht bewölkt',
    BEWOELKUNG_WOLKIG: 'wolkig',
    BEWOELKUNG_BEDECKT: 'bedeckt',

    NEBEL: 'Nebel',
    NEBEL_LEICHT: 'unter 1000 m',
    NEBEL_DICHT: 'unter 200 m',
    NEBEL_EXTREM: 'unter 50 m',

    TORNADO: 'Tornado',
    TORNADO_NO_VISIBLE_DAMAGE: 'keine Schäden sichtbar',
    TORNADO_F0: 'leicht',
    TORNADO_F1: 'moderat',
    TORNADO_F2: 'signifikant',
    TORNADO_F3: 'schwer',
    TORNADO_F4: 'verheerend',

    STATUS_TITLE: 'Zusammenfassung',
    REPORTER_DETAILS_LINK: 'Möchten Sie Ihren Namen und Beschreibung?',
    REPORTER_NAME_LABEL: 'Name (optional)',
    REPORTER_NAME_PLACEHOLDER: 'Ihr Name',
    REPORTER_DESCRIPTION_LABEL: 'Beschreibung (optional)',
    REPORTER_DESCRIPTION_PLACEHOLDER: 'Kleine Beschreibung eingeben',
};

export default deStrings;
