const enStrings: Record<string, string> = {
    RATE_LIMIT_WARNING: '⚠️ You can only submit a weather report once every 10 minutes.',
    REPORT_SUCCESS: 'Weather report sent successfully!',
    REPORT_ERROR: 'Error sending weather report!',
    BACK: 'Back',
    NEXT: 'Next',
    CATEGORIES_TITLE: 'Categories',
    LOCATION_TITLE: 'Location',
    TIME_TITLE: 'Time',
    TIME_NOW: 'now',
    TIME_10_MINUTES: '10 minutes ago',
    TIME_20_MINUTES: '20 minutes ago',
    TIME_30_MINUTES: '30 minutes ago',
    TIME_60_MINUTES: '1 hour ago',
    IMAGE_UPLOAD_TITLE: 'Upload Image',
    IMAGE_UPLOAD_DESCRIPTION: 'Upload an image (max. 10MB). Supported formats: JPG, PNG, GIF, WEBP',
    IMAGE_UPLOAD_SUCCESS: '✅ Image uploaded successfully!',
    IMAGE_UPLOAD_REMOVE: 'Remove image',
    IMAGE_UPLOAD_PROGRESS: 'Uploading...',
    IMAGE_UPLOAD_DROP_FILE: 'Drop file here...',
    IMAGE_UPLOAD_SELECT: 'Select image',
    IMAGE_UPLOAD_HINT: 'Click to select a file or drag a file here',
    IMAGE_UPLOAD_DRAG_INSTRUCTION: 'or drag in here',
    IMAGE_UPLOAD_PREVIEW_ALT: 'Preview',
    ERROR_FILE_TOO_LARGE: 'File is too large. Maximum size: 10MB',
    ERROR_INVALID_FILE_TYPE: 'Only image files are allowed (JPG, PNG, GIF, WEBP)',
    ERROR_GENERIC_UPLOAD: 'Error uploading file',
    ERROR_NETWORK_UPLOAD: 'Network error during upload',
    ERROR_UPLOAD_WITH_STATUS: 'Error uploading:',

    BLITZE: 'Lightning',
    DONNER_UMGEBUNG: 'Thunder in the vicinity',
    BLITZE_EINZELNE: 'weak',
    BLITZE_HAEUFIG: 'strong',
    BLITZE_EXTREM: 'extreme',

    WIND: 'Wind',
    WIND_SCHWACH: 'weak',
    WIND_STARK: 'strong',
    WIND_STUERMISCH: 'stormy',
    WIND_STURM: 'Storm',
    WIND_ORKAN: 'Hurricane',

    HAGEL: 'Hail',
    HAGEL_UNTER_1CM: 'less than 1 cm',
    HAGEL_1CM: '1 cm',
    HAGEL_2CM: '2 cm',
    HAGEL_3CM: '3 cm',
    HAGEL_5CM: '5 cm',
    HAGEL_UEBER_7CM: 'over 7 cm',

    HAGEL_GESCHLOSSENE_HAGELDECKE: 'closed hail cover',
    HAGEL_SCHADEN_PFLANZEN: 'Damage to plants',
    HAGEL_SCHADEN_DACHFENSTER: 'Breakage of skylights and greenhouses',
    HAGEL_SCHADEN_VEREINZELT: 'isolated damage to roof tiles, window panes and facades',
    HAGEL_SCHADEN_ZERSTOERERISCH: 'destructive damage to roofs, windows and vehicles',

    REGEN: 'Rain',
    REGEN_LEICHT: 'light',
    REGEN_MITTEL: 'moderate',
    REGEN_KRAEFTIG: 'heavy',
    REGEN_STARK: 'strong',
    REGEN_EXTREM: 'extreme',

    GLAETTE: 'Ice',
    GLAETTE_REIF: 'Hoar frost',
    GLAETTE_SCHNEE: 'Snow slickness',
    GLAETTE_UEBERFRIERENDE_NAESSE: 'freezing wetness',
    GLAETTE_GEFRIERENDER_REGEN: 'freezing rain',

    GLAETTE_GESCHLOSSENE_SCHICHT: 'closed layer',
    GLAETTE_DICKE_ICE_UEBER_1CM: 'over 1 cm (finger thick)',
    GLAETTE_DICKE_ICE_BIS_1CM: 'under 1 cm (corrugated cardboard)',
    GLAETTE_DICKE_SNOW_BIS_5CM: 'under 5 cm',
    GLAETTE_DICKE_SNOW_BIS_20CM: 'under 20 cm',
    GLAETTE_DICKE_SNOW_BIS_50CM: 'under 50 cm',
    GLAETTE_DICKE_SNOW_UEBER_50CM: 'over 50 cm',

    SCHNEEFALL: 'Snowfall',
    SCHNEEFALL_WENIGE_FLOCKEN: 'few flakes',
    SCHNEEFALL_LEICHT: 'light',
    SCHNEEFALL_MITTEL: 'moderate',
    SCHNEEFALL_STARK: 'heavy',

    SCHNEEDECKE: 'Snow cover',
    SCHNEEDECKE_SCHNEEMATSCH: 'Slush',
    SCHNEEDECKE_BIS_1CM: 'up to 1 cm',
    SCHNEEDECKE_BIS_3CM: 'up to 3 cm',
    SCHNEEDECKE_BIS_5CM: 'up to 5 cm',
    SCHNEEDECKE_BIS_10CM: 'up to 10 cm',
    SCHNEEDECKE_BIS_20CM: 'up to 20 cm',
    SCHNEEDECKE_BIS_50CM: 'up to 50 cm',
    SCHNEEDECKE_UEBER_50CM: 'over 50 cm',

    SCHNEEDECKE_FLECKWEISE: 'Snow patches',
    SCHNEEDECKE_GESCHLOSSENE_SCHNEEDECKE: 'closed snow cover',

    BEWOELKUNG: 'Cloudiness',
    BEWOELKUNG_WOLKENLOS: 'clear',
    BEWOELKUNG_LEICHT_BEWOELKT: 'slightly cloudy',
    BEWOELKUNG_WOLKIG: 'cloudy',
    BEWOELKUNG_BEDECKT: 'overcast',

    NEBEL: 'Fog',
    NEBEL_LEICHT: 'under 1000 m',
    NEBEL_DICHT: 'under 200 m',
    NEBEL_EXTREM: 'under 50 m',

    TORNADO: 'Tornado',
    TORNADO_NO_VISIBLE_DAMAGE: 'no visible damage',
    TORNADO_F0: 'light',
    TORNADO_F1: 'moderate',
    TORNADO_F2: 'significant',
    TORNADO_F3: 'severe',
    TORNADO_F4: 'devastating',

    STATUS_TITLE: 'Summary',
};

export default enStrings;
