const roStrings: Record<string, string> = {
    RATE_LIMIT_WARNING: '⚠️ Puteți trimite un raport meteo doar o dată la 10 minute.',
    REPORT_SUCCESS: 'Raport meteo trimis cu succes!',
    REPORT_ERROR: 'Eroare la trimiterea raportului meteo!',
    BACK: 'Înapoi',
    NEXT: 'Înainte',
    CATEGORIES_TITLE: 'Categorii',
    LOCATION_TITLE: 'Locație',
    TIME_TITLE: 'Timp',
    TIME_NOW: 'acum',
    TIME_10_MINUTES: 'acum 10 minute',
    TIME_20_MINUTES: 'acum 20 minute',
    TIME_30_MINUTES: 'acum 30 minute',
    TIME_60_MINUTES: 'acum o oră',
    IMAGE_UPLOAD_TITLE: 'Încărcare imagine',
    IMAGE_UPLOAD_DESCRIPTION: 'Încărcați o imagine (max. 10MB). Formate acceptate: JPG, PNG, GIF, WEBP',
    IMAGE_UPLOAD_SUCCESS: '✅ Imagine încărcată cu succes!',
    IMAGE_UPLOAD_REMOVE: 'Șterge imaginea',
    IMAGE_UPLOAD_PROGRESS: 'Se încarcă...',
    IMAGE_UPLOAD_DROP_FILE: 'Plasați fișierul aici...',
    IMAGE_UPLOAD_SELECT: 'Selectați imaginea',
    IMAGE_UPLOAD_HINT: 'Faceți clic pentru a selecta un fișier sau trageți un fișier aici',
    IMAGE_UPLOAD_DRAG_INSTRUCTION: 'sau trageți aici',
    IMAGE_UPLOAD_PREVIEW_ALT: 'Previzualizare',
    ERROR_FILE_TOO_LARGE: 'Fișierul este prea mare. Dimensiune maximă: 10MB',
    ERROR_INVALID_FILE_TYPE: 'Sunt permise doar fișiere imagine (JPG, PNG, GIF, WEBP)',
    ERROR_GENERIC_UPLOAD: 'Eroare la încărcarea fișierului',
    ERROR_NETWORK_UPLOAD: 'Eroare de rețea la încărcare',
    ERROR_UPLOAD_WITH_STATUS: 'Eroare la încărcare:',

    BLITZE: 'Fulgere',
    DONNER_UMGEBUNG: 'Tunete în apropiere',
    BLITZE_EINZELNE: 'slabe',
    BLITZE_HAEUFIG: 'puternice',
    BLITZE_EXTREM: 'extreme',

    WIND: 'Vânt',
    WIND_SCHWACH: 'slab',
    WIND_STARK: 'puternic',
    WIND_STUERMISCH: 'furtunos',
    WIND_STURM: 'Furtună',
    WIND_ORKAN: 'Uragan',

    HAGEL: 'Grindină',
    HAGEL_UNTER_1CM: 'sub 1 cm',
    HAGEL_1CM: '1 cm',
    HAGEL_2CM: '2 cm',
    HAGEL_3CM: '3 cm',
    HAGEL_5CM: '5 cm',
    HAGEL_UEBER_7CM: 'peste 7 cm',

    HAGEL_GESCHLOSSENE_HAGELDECKE: 'strat de grindină compact',
    HAGEL_SCHADEN_PFLANZEN: 'Daune la plante',
    HAGEL_SCHADEN_DACHFENSTER: 'Spargerea luminatoarelor și a serelor',
    HAGEL_SCHADEN_VEREINZELT: 'daune izolate la țigle, geamuri și fațade',
    HAGEL_SCHADEN_ZERSTOERERISCH: 'daune distructive la acoperișuri, ferestre și vehicule',

    REGEN: 'Ploaie',
    REGEN_LEICHT: 'ușoară',
    REGEN_MITTEL: 'moderată',
    REGEN_KRAEFTIG: 'torențială',
    REGEN_STARK: 'puternică',
    REGEN_EXTREM: 'extremă',

    GLAETTE: 'Polei',
    GLAETTE_REIF: 'Chiciură',
    GLAETTE_SCHNEE: 'Zăpadă alunecoasă',
    GLAETTE_UEBERFRIERENDE_NAESSE: 'umezeală care îngheață',
    GLAETTE_GEFRIERENDER_REGEN: 'ploaie înghețată',

    GLAETTE_GESCHLOSSENE_SCHICHT: 'strat compact',
    GLAETTE_DICKE_ICE_UEBER_1CM: 'peste 1 cm (grosimea degetului)',
    GLAETTE_DICKE_ICE_BIS_1CM: 'sub 1 cm (carton ondulat)',
    GLAETTE_DICKE_SNOW_BIS_5CM: 'sub 5 cm',
    GLAETTE_DICKE_SNOW_BIS_20CM: 'sub 20 cm',
    GLAETTE_DICKE_SNOW_BIS_50CM: 'sub 50 cm',
    GLAETTE_DICKE_SNOW_UEBER_50CM: 'peste 50 cm',

    SCHNEEFALL: 'Ninsoare',
    SCHNEEFALL_WENIGE_FLOCKEN: 'câțiva fulgi',
    SCHNEEFALL_LEICHT: 'ușoară',
    SCHNEEFALL_MITTEL: 'moderată',
    SCHNEEFALL_STARK: 'puternică',

    SCHNEEDECKE: 'Strat de zăpadă',
    SCHNEEDECKE_SCHNEEMATSCH: 'Lapoviță',
    SCHNEEDECKE_BIS_1CM: 'până la 1 cm',
    SCHNEEDECKE_BIS_3CM: 'până la 3 cm',
    SCHNEEDECKE_BIS_5CM: 'până la 5 cm',
    SCHNEEDECKE_BIS_10CM: 'până la 10 cm',
    SCHNEEDECKE_BIS_20CM: 'până la 20 cm',
    SCHNEEDECKE_BIS_50CM: 'până la 50 cm',
    SCHNEEDECKE_UEBER_50CM: 'peste 50 cm',

    SCHNEEDECKE_FLECKWEISE: 'Pete de zăpadă',
    SCHNEEDECKE_GESCHLOSSENE_SCHNEEDECKE: 'strat de zăpadă compact',

    BEWOELKUNG: 'Înnorare',
    BEWOELKUNG_WOLKENLOS: 'senin',
    BEWOELKUNG_LEICHT_BEWOELKT: 'parțial noros',
    BEWOELKUNG_WOLKIG: 'noros',
    BEWOELKUNG_BEDECKT: 'înnorat',

    NEBEL: 'Ceață',
    NEBEL_LEICHT: 'sub 1000 m',
    NEBEL_DICHT: 'sub 200 m',
    NEBEL_EXTREM: 'sub 50 m',

    TORNADO: 'Tornadă',
    TORNADO_NO_VISIBLE_DAMAGE: 'fără daune vizibile',
    TORNADO_F0: 'ușoară',
    TORNADO_F1: 'moderată',
    TORNADO_F2: 'semnificativă',
    TORNADO_F3: 'severă',
    TORNADO_F4: 'devastatoare',
};

export default roStrings;
