export type SupportedLanguage = 'de' | 'en' | 'ro';

const DEFAULT_LANGUAGE: SupportedLanguage = 'de';

export const STRINGS: Record<SupportedLanguage, Record<string, string>> = {
    de: {
        RATE_LIMIT_WARNING: '⚠️ Sie können nur einmal innerhalb von 10 Minuten eine Wettermeldung absetzen.',
        REPORT_SUCCESS: 'Wettermeldung erfolgreich gesendet!',
        REPORT_ERROR: 'Fehler beim Senden der Wettermeldung!',
        BACK: 'Zurück',
        NEXT: 'Weiter',
        CATEGORIES_TITLE: 'Kategorien',
        LOCATION_TITLE: 'Standort',
        TIME_TITLE: 'Zeit',
        TIME_NOW: 'jetzt',
        TIME_10_MINUTES: 'vor 10 Minuten',
        TIME_20_MINUTES: 'vor 20 Minuten',
        TIME_30_MINUTES: 'vor 30 Minuten',
        TIME_60_MINUTES: 'vor eine Stunde',
        IMAGE_UPLOAD_TITLE: 'Bild hochladen',
        IMAGE_UPLOAD_DESCRIPTION: 'Laden Sie ein Bild hoch (max. 10MB). Unterstützte Formate: JPG, PNG, GIF, WEBP',
        IMAGE_UPLOAD_SUCCESS: '✅ Bild erfolgreich hochgeladen!',
        IMAGE_UPLOAD_REMOVE: 'Bild entfernen',
        IMAGE_UPLOAD_PROGRESS: 'Hochladen...',
        IMAGE_UPLOAD_DROP_FILE: 'Datei hier ablegen...',
        IMAGE_UPLOAD_SELECT: 'Bild auswählen',
        IMAGE_UPLOAD_HINT: 'Klicken Sie, um eine Datei auszuwählen, oder ziehen Sie eine Datei hierher',
        IMAGE_UPLOAD_DRAG_INSTRUCTION: 'oder hier hineinziehen',
        IMAGE_UPLOAD_PREVIEW_ALT: 'Vorschau',
        ERROR_FILE_TOO_LARGE: 'Datei ist zu groß. Maximale Größe: 10MB',
        ERROR_INVALID_FILE_TYPE: 'Nur Bilddateien sind erlaubt (JPG, PNG, GIF, WEBP)',
        ERROR_GENERIC_UPLOAD: 'Fehler beim Hochladen der Datei',
        ERROR_NETWORK_UPLOAD: 'Netzwerkfehler beim Hochladen',
        ERROR_UPLOAD_WITH_STATUS: 'Fehler beim Hochladen:',

        BLITZE: 'Blitze',
        DONNER_UMGEBUNG: 'Donner in der Umgebung',
        BLITZE_EINZELNE: 'schwach',
        BLITZE_HAEUFIG: 'stark',
        BLITZE_EXTREM: 'extrem',

        WIND: 'Wind',
        WIND_SCHWACH: 'schwach',
        WIND_STARK: 'stark',
        WIND_STUERMISCH: 'stürmisch',
        WIND_STURM: 'Sturm',
        WIND_ORKAN: 'Orkan',

        HAGEL: 'Hagel',
        HAGEL_UNTER_1CM: 'unter 1 cm',
        HAGEL_1CM: '1 cm',
        HAGEL_2CM: '2 cm',
        HAGEL_3CM: '3 cm',
        HAGEL_5CM: '5 cm',
        HAGEL_UEBER_7CM: 'über 7 cm',

        HAGEL_GESCHLOSSENE_HAGELDECKE: 'geschlossene Hageldecke',
        HAGEL_SCHADEN_PFLANZEN: 'Schäden an Pflenzen',
        HAGEL_SCHADEN_DACHFENSTER: 'Bruch von Dachfenstern und Gewächshäusern',
        HAGEL_SCHADEN_VEREINZELT: 'vereinzelte Schäden an Dachziegel, Fensterscheiben und Fassaden',
        HAGEL_SCHADEN_ZERSTOERERISCH: 'zerstörische Schäden an Dächern, Fenstern und Fahrzeugen',

        REGEN: 'Regen',
        REGEN_LEICHT: 'leicht',
        REGEN_MITTEL: 'mittel',
        REGEN_KRAEFTIG: 'kräftig',
        REGEN_STARK: 'stark',
        REGEN_EXTREM: 'extrem',

        GLAETTE: 'Glätte',
        GLAETTE_REIF: 'Reifglätte',
        GLAETTE_SCHNEE: 'Schneeglätte',
        GLAETTE_UEBERFRIERENDE_NAESSE: 'überfrierende Nässe',
        GLAETTE_GEFRIERENDER_REGEN: 'gefrierender Regen',

        GLAETTE_GESCHLOSSENE_SCHICHT: 'geschlossene Schicht',
        GLAETTE_DICKE_ICE_UEBER_1CM: 'über 1 cm (Fingerdick',
        GLAETTE_DICKE_ICE_BIS_1CM: 'unter 1 cm (Wellpappe)',
        GLAETTE_DICKE_SNOW_BIS_5CM: 'unter 5 cm',
        GLAETTE_DICKE_SNOW_BIS_20CM: 'unter 20 cm',
        GLAETTE_DICKE_SNOW_BIS_50CM: 'unter 50 cm',
        GLAETTE_DICKE_SNOW_UEBER_50CM: 'über 50 cm',

        SCHNEEFALL: 'Schneefall',
        SCHNEEFALL_WENIGE_FLOCKEN: 'wenige Flocken',
        SCHNEEFALL_LEICHT: 'leicht',
        SCHNEEFALL_MITTEL: 'mittel',
        SCHNEEFALL_STARK: 'stark',

        SCHNEEDECKE: 'Schneedecke',
        SCHNEEDECKE_SCHNEEMATSCH: 'Schneematsch',
        SCHNEEDECKE_BIS_1CM: 'bis 1 cm',
        SCHNEEDECKE_BIS_3CM: 'bis zu 3 cm',
        SCHNEEDECKE_BIS_5CM: 'bis zu 5 cm',
        SCHNEEDECKE_BIS_10CM: 'bis zu 10 cm',
        SCHNEEDECKE_BIS_20CM: 'bis zu 20 cm',
        SCHNEEDECKE_BIS_50CM: 'bis zu 50 cm',
        SCHNEEDECKE_UEBER_50CM: 'über 50 cm',

        SCHNEEDECKE_FLECKWEISE: 'Schneeflecken',
        SCHNEEDECKE_GESCHLOSSENE_SCHNEEDECKE: 'geschlossene Schneedecke',

        BEWOELKUNG: 'Bewölkung',
        BEWOELKUNG_WOLKENLOS: 'wolkenlos',
        BEWOELKUNG_LEICHT_BEWOELKT: 'leicht bewölkt',
        BEWOELKUNG_WOLKIG: 'wolkig',
        BEWOELKUNG_BEDECKT: 'bedeckt',

        NEBEL: 'Nebel',
        NEBEL_LEICHT: 'unter 1000 m',
        NEBEL_DICHT: 'unter 200 m',
        NEBEL_EXTREM: 'unter 50 m',

        TORNADO: 'Tornado',
        TORNADO_NO_VISIBLE_DAMAGE: 'keine Schäden sichtbar',
        TORNADO_F0: 'leicht',
        TORNADO_F1: 'moderat',
        TORNADO_F2: 'signifikant',
        TORNADO_F3: 'schwer',
        TORNADO_F4: 'verheerend',
    },
    en: {
        RATE_LIMIT_WARNING: '⚠️ You can only submit a weather report once every 10 minutes.',
        REPORT_SUCCESS: 'Weather report sent successfully!',
        REPORT_ERROR: 'Error sending weather report!',
        BACK: 'Back',
        NEXT: 'Next',
        CATEGORIES_TITLE: 'Categories',
        LOCATION_TITLE: 'Location',
        TIME_TITLE: 'Time',
        TIME_NOW: 'now',
        TIME_10_MINUTES: '10 minutes ago',
        TIME_20_MINUTES: '20 minutes ago',
        TIME_30_MINUTES: '30 minutes ago',
        TIME_60_MINUTES: '1 hour ago',
        IMAGE_UPLOAD_TITLE: 'Upload Image',
        IMAGE_UPLOAD_DESCRIPTION: 'Upload an image (max. 10MB). Supported formats: JPG, PNG, GIF, WEBP',
        IMAGE_UPLOAD_SUCCESS: '✅ Image uploaded successfully!',
        IMAGE_UPLOAD_REMOVE: 'Remove image',
        IMAGE_UPLOAD_PROGRESS: 'Uploading...',
        IMAGE_UPLOAD_DROP_FILE: 'Drop file here...',
        IMAGE_UPLOAD_SELECT: 'Select image',
        IMAGE_UPLOAD_HINT: 'Click to select a file or drag a file here',
        IMAGE_UPLOAD_DRAG_INSTRUCTION: 'or drag in here',
        IMAGE_UPLOAD_PREVIEW_ALT: 'Preview',
        ERROR_FILE_TOO_LARGE: 'File is too large. Maximum size: 10MB',
        ERROR_INVALID_FILE_TYPE: 'Only image files are allowed (JPG, PNG, GIF, WEBP)',
        ERROR_GENERIC_UPLOAD: 'Error uploading file',
        ERROR_NETWORK_UPLOAD: 'Network error during upload',
        ERROR_UPLOAD_WITH_STATUS: 'Error uploading:',

        BLITZE: 'Lightning',
        DONNER_UMGEBUNG: 'Thunder in the vicinity',
        BLITZE_EINZELNE: 'weak',
        BLITZE_HAEUFIG: 'strong',
        BLITZE_EXTREM: 'extreme',

        WIND: 'Wind',
        WIND_SCHWACH: 'weak',
        WIND_STARK: 'strong',
        WIND_STUERMISCH: 'stormy',
        WIND_STURM: 'Storm',
        WIND_ORKAN: 'Hurricane',

        HAGEL: 'Hail',
        HAGEL_UNTER_1CM: 'less than 1 cm',
        HAGEL_1CM: '1 cm',
        HAGEL_2CM: '2 cm',
        HAGEL_3CM: '3 cm',
        HAGEL_5CM: '5 cm',
        HAGEL_UEBER_7CM: 'over 7 cm',

        HAGEL_GESCHLOSSENE_HAGELDECKE: 'closed hail cover',
        HAGEL_SCHADEN_PFLANZEN: 'Damage to plants',
        HAGEL_SCHADEN_DACHFENSTER: 'Breakage of skylights and greenhouses',
        HAGEL_SCHADEN_VEREINZELT: 'isolated damage to roof tiles, window panes and facades',
        HAGEL_SCHADEN_ZERSTOERERISCH: 'destructive damage to roofs, windows and vehicles',

        REGEN: 'Rain',
        REGEN_LEICHT: 'light',
        REGEN_MITTEL: 'moderate',
        REGEN_KRAEFTIG: 'heavy',
        REGEN_STARK: 'strong',
        REGEN_EXTREM: 'extreme',

        GLAETTE: 'Ice',
        GLAETTE_REIF: 'Hoar frost',
        GLAETTE_SCHNEE: 'Snow slickness',
        GLAETTE_UEBERFRIERENDE_NAESSE: 'freezing wetness',
        GLAETTE_GEFRIERENDER_REGEN: 'freezing rain',

        GLAETTE_GESCHLOSSENE_SCHICHT: 'closed layer',
        GLAETTE_DICKE_ICE_UEBER_1CM: 'over 1 cm (finger thick)',
        GLAETTE_DICKE_ICE_BIS_1CM: 'under 1 cm (corrugated cardboard)',
        GLAETTE_DICKE_SNOW_BIS_5CM: 'under 5 cm',
        GLAETTE_DICKE_SNOW_BIS_20CM: 'under 20 cm',
        GLAETTE_DICKE_SNOW_BIS_50CM: 'under 50 cm',
        GLAETTE_DICKE_SNOW_UEBER_50CM: 'over 50 cm',

        SCHNEEFALL: 'Snowfall',
        SCHNEEFALL_WENIGE_FLOCKEN: 'few flakes',
        SCHNEEFALL_LEICHT: 'light',
        SCHNEEFALL_MITTEL: 'moderate',
        SCHNEEFALL_STARK: 'heavy',

        SCHNEEDECKE: 'Snow cover',
        SCHNEEDECKE_SCHNEEMATSCH: 'Slush',
        SCHNEEDECKE_BIS_1CM: 'up to 1 cm',
        SCHNEEDECKE_BIS_3CM: 'up to 3 cm',
        SCHNEEDECKE_BIS_5CM: 'up to 5 cm',
        SCHNEEDECKE_BIS_10CM: 'up to 10 cm',
        SCHNEEDECKE_BIS_20CM: 'up to 20 cm',
        SCHNEEDECKE_BIS_50CM: 'up to 50 cm',
        SCHNEEDECKE_UEBER_50CM: 'over 50 cm',

        SCHNEEDECKE_FLECKWEISE: 'Snow patches',
        SCHNEEDECKE_GESCHLOSSENE_SCHNEEDECKE: 'closed snow cover',

        BEWOELKUNG: 'Cloudiness',
        BEWOELKUNG_WOLKENLOS: 'clear',
        BEWOELKUNG_LEICHT_BEWOELKT: 'slightly cloudy',
        BEWOELKUNG_WOLKIG: 'cloudy',
        BEWOELKUNG_BEDECKT: 'overcast',

        NEBEL: 'Fog',
        NEBEL_LEICHT: 'under 1000 m',
        NEBEL_DICHT: 'under 200 m',
        NEBEL_EXTREM: 'under 50 m',

        TORNADO: 'Tornado',
        TORNADO_NO_VISIBLE_DAMAGE: 'no visible damage',
        TORNADO_F0: 'light',
        TORNADO_F1: 'moderate',
        TORNADO_F2: 'significant',
        TORNADO_F3: 'severe',
        TORNADO_F4: 'devastating',
    },
    ro: {
        RATE_LIMIT_WARNING: '⚠️ Puteți trimite un raport meteo doar o dată la 10 minute.',
        REPORT_SUCCESS: 'Raport meteo trimis cu succes!',
        REPORT_ERROR: 'Eroare la trimiterea raportului meteo!',
        BACK: 'Înapoi',
        NEXT: 'Înainte',
        CATEGORIES_TITLE: 'Categorii',
        LOCATION_TITLE: 'Locație',
        TIME_TITLE: 'Timp',
        TIME_NOW: 'acum',
        TIME_10_MINUTES: 'acum 10 minute',
        TIME_20_MINUTES: 'acum 20 minute',
        TIME_30_MINUTES: 'acum 30 minute',
        TIME_60_MINUTES: 'acum o oră',
        IMAGE_UPLOAD_TITLE: 'Încărcare imagine',
        IMAGE_UPLOAD_DESCRIPTION: 'Încărcați o imagine (max. 10MB). Formate acceptate: JPG, PNG, GIF, WEBP',
        IMAGE_UPLOAD_SUCCESS: '✅ Imagine încărcată cu succes!',
        IMAGE_UPLOAD_REMOVE: 'Șterge imaginea',
        IMAGE_UPLOAD_PROGRESS: 'Se încarcă...',
        IMAGE_UPLOAD_DROP_FILE: 'Plasați fișierul aici...',
        IMAGE_UPLOAD_SELECT: 'Selectați imaginea',
        IMAGE_UPLOAD_HINT: 'Faceți clic pentru a selecta un fișier sau trageți un fișier aici',
        IMAGE_UPLOAD_DRAG_INSTRUCTION: 'sau trageți aici',
        IMAGE_UPLOAD_PREVIEW_ALT: 'Previzualizare',
        ERROR_FILE_TOO_LARGE: 'Fișierul este prea mare. Dimensiune maximă: 10MB',
        ERROR_INVALID_FILE_TYPE: 'Sunt permise doar fișiere imagine (JPG, PNG, GIF, WEBP)',
        ERROR_GENERIC_UPLOAD: 'Eroare la încărcarea fișierului',
        ERROR_NETWORK_UPLOAD: 'Eroare de rețea la încărcare',
        ERROR_UPLOAD_WITH_STATUS: 'Eroare la încărcare:',

        BLITZE: 'Fulgere',
        DONNER_UMGEBUNG: 'Tunete în apropiere',
        BLITZE_EINZELNE: 'slabe',
        BLITZE_HAEUFIG: 'puternice',
        BLITZE_EXTREM: 'extreme',

        WIND: 'Vânt',
        WIND_SCHWACH: 'slab',
        WIND_STARK: 'puternic',
        WIND_STUERMISCH: 'furtunos',
        WIND_STURM: 'Furtună',
        WIND_ORKAN: 'Uragan',

        HAGEL: 'Grindină',
        HAGEL_UNTER_1CM: 'sub 1 cm',
        HAGEL_1CM: '1 cm',
        HAGEL_2CM: '2 cm',
        HAGEL_3CM: '3 cm',
        HAGEL_5CM: '5 cm',
        HAGEL_UEBER_7CM: 'peste 7 cm',

        HAGEL_GESCHLOSSENE_HAGELDECKE: 'strat de grindină compact',
        HAGEL_SCHADEN_PFLANZEN: 'Daune la plante',
        HAGEL_SCHADEN_DACHFENSTER: 'Spargerea luminatoarelor și a serelor',
        HAGEL_SCHADEN_VEREINZELT: 'daune izolate la țigle, geamuri și fațade',
        HAGEL_SCHADEN_ZERSTOERERISCH: 'daune distructive la acoperișuri, ferestre și vehicule',

        REGEN: 'Ploaie',
        REGEN_LEICHT: 'ușoară',
        REGEN_MITTEL: 'moderată',
        REGEN_KRAEFTIG: 'torențială',
        REGEN_STARK: 'puternică',
        REGEN_EXTREM: 'extremă',

        GLAETTE: 'Polei',
        GLAETTE_REIF: 'Chiciură',
        GLAETTE_SCHNEE: 'Zăpadă alunecoasă',
        GLAETTE_UEBERFRIERENDE_NAESSE: 'umezeală care îngheață',
        GLAETTE_GEFRIERENDER_REGEN: 'ploaie înghețată',

        GLAETTE_GESCHLOSSENE_SCHICHT: 'strat compact',
        GLAETTE_DICKE_ICE_UEBER_1CM: 'peste 1 cm (grosimea degetului)',
        GLAETTE_DICKE_ICE_BIS_1CM: 'sub 1 cm (carton ondulat)',
        GLAETTE_DICKE_SNOW_BIS_5CM: 'sub 5 cm',
        GLAETTE_DICKE_SNOW_BIS_20CM: 'sub 20 cm',
        GLAETTE_DICKE_SNOW_BIS_50CM: 'sub 50 cm',
        GLAETTE_DICKE_SNOW_UEBER_50CM: 'peste 50 cm',

        SCHNEEFALL: 'Ninsoare',
        SCHNEEFALL_WENIGE_FLOCKEN: 'câțiva fulgi',
        SCHNEEFALL_LEICHT: 'ușoară',
        SCHNEEFALL_MITTEL: 'moderată',
        SCHNEEFALL_STARK: 'puternică',

        SCHNEEDECKE: 'Strat de zăpadă',
        SCHNEEDECKE_SCHNEEMATSCH: 'Lapoviță',
        SCHNEEDECKE_BIS_1CM: 'până la 1 cm',
        SCHNEEDECKE_BIS_3CM: 'până la 3 cm',
        SCHNEEDECKE_BIS_5CM: 'până la 5 cm',
        SCHNEEDECKE_BIS_10CM: 'până la 10 cm',
        SCHNEEDECKE_BIS_20CM: 'până la 20 cm',
        SCHNEEDECKE_BIS_50CM: 'până la 50 cm',
        SCHNEEDECKE_UEBER_50CM: 'peste 50 cm',

        SCHNEEDECKE_FLECKWEISE: 'Pete de zăpadă',
        SCHNEEDECKE_GESCHLOSSENE_SCHNEEDECKE: 'strat de zăpadă compact',

        BEWOELKUNG: 'Înnorare',
        BEWOELKUNG_WOLKENLOS: 'senin',
        BEWOELKUNG_LEICHT_BEWOELKT: 'parțial noros',
        BEWOELKUNG_WOLKIG: 'noros',
        BEWOELKUNG_BEDECKT: 'înnorat',

        NEBEL: 'Ceață',
        NEBEL_LEICHT: 'sub 1000 m',
        NEBEL_DICHT: 'sub 200 m',
        NEBEL_EXTREM: 'sub 50 m',

        TORNADO: 'Tornadă',
        TORNADO_NO_VISIBLE_DAMAGE: 'fără daune vizibile',
        TORNADO_F0: 'ușoară',
        TORNADO_F1: 'moderată',
        TORNADO_F2: 'semnificativă',
        TORNADO_F3: 'severă',
        TORNADO_F4: 'devastatoare',
    },
};

export const getString = (lang: string, key: string): string => {
    const language = (lang as SupportedLanguage) in STRINGS ? (lang as SupportedLanguage) : DEFAULT_LANGUAGE;
    return STRINGS[language][key] ?? STRINGS[DEFAULT_LANGUAGE][key] ?? key;
};
